# This workflow will build and test the server, and build the site.
# It will also package the server and the site up as Docker images, and push them to the configured 
# repository.
# This is only run on master, and is only intended for changes that have been reviewed and approved 
# for deployment.

name: Test and deploy

on:
  push:
    branches: [ master ]

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run the package goal with Maven
        run: |
          mvn package -pl fhir-server -am -DskipShade \
          -DfhirServerDockerRepo=${{ secrets.FHIR_SERVER_DOCKER_REPO }}
      - uses: actions/upload-artifact@v2
        with:
          name: encoders-surefire-reports
          path: encoders/target/surefire-reports
      - uses: actions/upload-artifact@v2
        with:
          name: fhir-server-surefire-reports
          path: fhir-server/target/surefire-reports
      - name: Tag and push server image
        run: |
          mvn dockerfile:tag@tag-major dockerfile:tag@tag-latest dockerfile:push@push-version \
          dockerfile:push@push-major dockerfile:push@push-latest -pl fhir-server \
          -DfhirServerDockerRepo=${{ secrets.FHIR_SERVER_DOCKER_REPO }} \
          -Ddockerfile.username=${{ secrets.DOCKER_USERNAME }} \
          -Ddockerfile.password=${{ secrets.DOCKER_PASSWORD }}
  site:
    name: Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/site
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Install the bundle
        run: bundle
      - name: Build the site with Jekyll
        run: bundle exec jekyll build
      - name: Build and push site image
        uses: docker/build-push-action@v1
        with:
          path: site
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.SITE_DOCKER_REPO }}